src/AvTranscoder/mediaProperty/VideoProperties.cpp, src/AvTranscoder/mediaProperty/VideoProperties.hpp
* fix gop analyse.
* need to patch for isClosedGop function.
=> Closed gop

COPYING.md, LICENSE.GPL, LICENSE.LGPL, README.md
=> Add multi-licensing

src/AvTranscoder/codec/ICodec.cpp
=> ICodec: loadCodecOptions when constructor object from an existing libav object

app/avProcessor/avProcessor.cpp, src/AvTranscoder/decoder/AudioDecoder.cpp, src/AvTranscoder/decoder/AudioDecoder.hpp, src/AvTranscoder/decoder/VideoDecoder.cpp, src/AvTranscoder/encoder/AudioEncoder.cpp, src/AvTranscoder/encoder/VideoEncoder.cpp, src/AvTranscoder/file/IOutputFile.hpp, src/AvTranscoder/file/OutputFile.cpp, src/AvTranscoder/file/OutputFile.hpp, src/AvTranscoder/file/file.i, src/AvTranscoder/stream/IOutputStream.hpp, src/AvTranscoder/stream/OutputStream.cpp, src/AvTranscoder/stream/OutputStream.hpp, src/AvTranscoder/transcoder/StreamTranscoder.cpp, src/AvTranscoder/transcoder/StreamTranscoder.hpp, src/AvTranscoder/transcoder/Transcoder.cpp, src/AvTranscoder/transcoder/Transcoder.hpp
=> Set threads option to auto by default

src/AvTranscoder/ProfileLoader.cpp, src/AvTranscoder/ProfileLoader.hpp, src/AvTranscoder/avTranscoder.i, src/AvTranscoder/codec/ICodec.hpp, src/AvTranscoder/common.cpp, src/AvTranscoder/common.hpp, src/AvTranscoder/file/OutputFile.cpp, src/AvTranscoder/frame/VideoFrame.hpp, src/AvTranscoder/mediaProperty/VideoProperties.cpp, src/AvTranscoder/mediaProperty/VideoProperties.hpp, src/AvTranscoder/mediaProperty/util.cpp, src/AvTranscoder/mediaProperty/util.hpp, src/AvTranscoder/swig/avLogLevel.i, src/AvTranscoder/swig/avMediaType.i, src/AvTranscoder/swig/avRational.i, src/AvTranscoder/util.cpp, src/AvTranscoder/util.hpp
Add log levels in SWIG interface.
Add AVMediaType in SWIG interface.
=> Add setLogLevel

src/AvTranscoder/transcoder/Transcoder.cpp, src/AvTranscoder/transcoder/Transcoder.hpp
Stop transcode at the end of an indicated duration.
=> Add transcoding policy eProcessMethodBasedOnDuration

src/AvTranscoder/file/IOutputFile.hpp, src/AvTranscoder/frame/AudioFrame.cpp, src/AvTranscoder/frame/AudioFrame.hpp, src/AvTranscoder/frame/Frame.cpp, src/AvTranscoder/frame/Frame.hpp, src/AvTranscoder/frame/VideoFrame.cpp, src/AvTranscoder/frame/VideoFrame.hpp
Frame: add copyData to copy an external data buffer.
AudioFrameDesc: can set all parameters from a given profile.
=> Clean frame

ressource/v_proresHQ.prf, ressource/v_proresProxy.prf
* prores HQ
* prores Proxy
* See https://transcoding.wordpress.com/2012/01/29/prores-ffmpeg/
* Fix #83
=> Add profiles for prores

src/AvTranscoder/ProfileLoader.hpp, src/AvTranscoder/decoder/AudioDecoder.cpp, src/AvTranscoder/decoder/VideoDecoder.cpp, src/AvTranscoder/encoder/AudioEncoder.cpp, src/AvTranscoder/encoder/VideoEncoder.cpp, src/AvTranscoder/transcoder/StreamTranscoder.cpp
=> Encoders/Decoders: fix threads option when indicated in profile

src/AvTranscoder/encoder/AudioEncoder.cpp, src/AvTranscoder/encoder/AudioEncoder.hpp, src/AvTranscoder/encoder/VideoEncoder.cpp, src/AvTranscoder/encoder/VideoEncoder.hpp
=> Encoders: allocate AVFrame once

src/AvTranscoder/file/OutputFile.cpp
=> Clean OutputFile::wrap

src/AvTranscoder/Option.cpp, src/AvTranscoder/codec/ICodec.cpp, src/AvTranscoder/common.cpp, src/AvTranscoder/common.hpp, src/AvTranscoder/decoder/AudioDecoder.cpp, src/AvTranscoder/decoder/VideoDecoder.cpp, src/AvTranscoder/encoder/AudioEncoder.cpp, src/AvTranscoder/encoder/VideoEncoder.cpp, src/AvTranscoder/file/FormatContext.cpp
Clean check of these errors by adding getDescriptionFromErrorCode function in common.hpp
=> Check FFmpeg error in FormatContext

src/AvTranscoder/avTranscoder.i, src/AvTranscoder/common.hpp, src/AvTranscoder/decoder/AudioDecoder.hpp, src/AvTranscoder/decoder/VideoDecoder.hpp, src/AvTranscoder/encoder/AudioEncoder.hpp, src/AvTranscoder/encoder/VideoEncoder.hpp, src/AvTranscoder/file/IOutputFile.hpp, src/AvTranscoder/file/InputFile.hpp, src/AvTranscoder/frame/AudioFrame.hpp, src/AvTranscoder/frame/VideoFrame.hpp, src/AvTranscoder/profile/ProfileLoader.cpp, src/AvTranscoder/profile/ProfileLoader.hpp, src/AvTranscoder/profile/profile.i, src/AvTranscoder/profile/util.hpp, src/AvTranscoder/system.hpp, src/AvTranscoder/transcoder/StreamTranscoder.hpp, src/AvTranscoder/transcoder/Transcoder.hpp
=> Load profiles on Windows

app/avProcessor/avProcessor.cpp, app/avThumbnail/avThumbnail.cpp, src/AvTranscoder/Option.cpp, src/AvTranscoder/ProfileLoader.cpp, src/AvTranscoder/codec/ICodec.cpp, src/AvTranscoder/common.cpp, src/AvTranscoder/common.hpp, src/AvTranscoder/decoder/AudioDecoder.cpp, src/AvTranscoder/decoder/VideoDecoder.cpp, src/AvTranscoder/encoder/AudioEncoder.cpp, src/AvTranscoder/encoder/VideoEncoder.cpp, src/AvTranscoder/file/FormatContext.cpp, src/AvTranscoder/file/InputFile.cpp, src/AvTranscoder/file/InputFile.hpp, src/AvTranscoder/file/OutputFile.cpp, src/AvTranscoder/file/OutputFile.hpp, src/AvTranscoder/log.cpp, src/AvTranscoder/log.hpp, src/AvTranscoder/mediaProperty/DataProperties.cpp, src/AvTranscoder/progress/IProgress.hpp, src/AvTranscoder/transcoder/StreamTranscoder.cpp, src/AvTranscoder/transcoder/StreamTranscoder.hpp, src/AvTranscoder/transcoder/Transcoder.cpp, src/AvTranscoder/transcoder/Transcoder.hpp, src/AvTranscoder/transform/VideoTransform.cpp, src/AvTranscoder/transform/VideoTransform.hpp
=> Add log system based on ffmpeg/libav

src/AvTranscoder/transform/AudioTransform.cpp, src/AvTranscoder/transform/AudioTransform.hpp
=> Fix AudioTransform:  when nbSamples change between frames

src/AvTranscoder/codec/ICodec.hpp, src/AvTranscoder/decoder/AudioGenerator.cpp, src/AvTranscoder/decoder/AudioGenerator.hpp, src/AvTranscoder/decoder/VideoGenerator.cpp, src/AvTranscoder/decoder/VideoGenerator.hpp, src/AvTranscoder/file/FormatContext.hpp, src/AvTranscoder/file/InputFile.hpp, src/AvTranscoder/file/OutputFile.hpp, src/AvTranscoder/frame/Frame.cpp, src/AvTranscoder/frame/Frame.hpp, src/AvTranscoder/mediaProperty/AudioProperties.hpp, src/AvTranscoder/stream/InputStream.cpp, src/AvTranscoder/stream/InputStream.hpp, src/AvTranscoder/transcoder/StreamTranscoder.hpp, src/AvTranscoder/transcoder/Transcoder.hpp, src/AvTranscoder/transform/AudioTransform.hpp, src/AvTranscoder/transform/VideoTransform.hpp
=> Add private copy constructors for some classes

src/AvTranscoder/mediaProperty/AttachementProperties.cpp, src/AvTranscoder/mediaProperty/AudioProperties.cpp, src/AvTranscoder/mediaProperty/AudioProperties.hpp, src/AvTranscoder/mediaProperty/DataProperties.cpp, src/AvTranscoder/mediaProperty/FileProperties.cpp, src/AvTranscoder/mediaProperty/FileProperties.hpp, src/AvTranscoder/mediaProperty/PixelProperties.cpp, src/AvTranscoder/mediaProperty/PixelProperties.hpp, src/AvTranscoder/mediaProperty/SubtitleProperties.cpp, src/AvTranscoder/mediaProperty/UnknownProperties.cpp, src/AvTranscoder/mediaProperty/VideoProperties.cpp, src/AvTranscoder/mediaProperty/VideoProperties.hpp, test/pyTest/testTranscoderRewrap.py
=> Dev media properties exceptions properties as map

ressource/v_h264.prf, ressource/v_h264_hq.prf, ressource/v_h264_lq.prf, src/AvTranscoder/profile/util.hpp
See https://trac.handbrake.fr/wiki/x264VideoSettings
=> Add presets h264 low/hq

.travis.yml, src/AvTranscoder/mediaProperty/VideoProperties.cpp, tools/travis.linux.install.deps.sh, tools/travis.osx.install.deps.sh
Fix #138
PR to launch Travis: do not merge for now!
=> Travis: use matrix to build with ffmpeg/libav

src/CMakeLists.txt, tools/travis.python.nosetests.sh
=> Deploy python lib with python interface

app/pyThumbnail/pythumbnail.py, src/AvTranscoder/file/FormatContext.cpp, src/AvTranscoder/file/FormatContext.hpp, src/AvTranscoder/file/InputFile.cpp, src/AvTranscoder/mediaProperty/FileProperties.cpp
=> Clean seek

ressource/v_dnxhd120.prf, ressource/v_dnxhd175x.prf, ressource/v_dnxhd185.prf, ressource/v_dnxhd185x.prf, ressource/v_dnxhd36.prf
=> Profiles: remove 'g' option from dnxhd profiles

src/AvTranscoder/mediaProperty/FileProperties.cpp, src/AvTranscoder/mediaProperty/FileProperties.hpp
Simplify StreamProperties access into the _getStreamPropertiesWithIndex()_ method
=> FileProperties: StreamProperties stored by streamIndex into a map

src/AvTranscoder/transcoder/Transcoder.cpp
=> Transcoder: log number of frame processed in debug

README.md, USAGE.md
=> Add USAGE.md

src/AvTranscoder/file/InputFile.cpp, src/AvTranscoder/file/InputFile.hpp, src/AvTranscoder/file/OutputFile.cpp, src/AvTranscoder/file/OutputFile.hpp, src/AvTranscoder/util.cpp, src/AvTranscoder/util.hpp
=> InputFile/OutputFile: can get format name/long name/mime type

app/pyProcessor/pyprocessor.py, app/pyThumbnail/pythumbnail.py
=> Fix python apps - python2.6

app/jFileAnalysis/jFileAnalysis.java
=> jFileAnalysis: clean

app/pyThumbnail/pythumbnail.py, src/AvTranscoder/file/InputFile.cpp, src/AvTranscoder/file/InputFile.hpp, src/AvTranscoder/file/OutputFile.cpp, src/AvTranscoder/file/OutputFile.hpp
=> Rename InputFile & OutputFile setProfile methods

src/AvTranscoder/decoder/AudioDecoder.cpp, src/AvTranscoder/decoder/AudioDecoder.hpp, src/AvTranscoder/decoder/AudioGenerator.hpp, src/AvTranscoder/decoder/IDecoder.hpp, src/AvTranscoder/decoder/VideoDecoder.cpp, src/AvTranscoder/decoder/VideoDecoder.hpp, src/AvTranscoder/decoder/VideoGenerator.hpp
=> decoders: the user can decode without any call to setup method

README.md
=> README: Travis badge display the result of the build on develop branch

.travis.yml, tools/travis.linux.install.deps.sh
=> Travis: switch to container-based infrastructure

src/AvTranscoder/file/OutputFile.cpp
Some codecs need / can use extradata like Huffman tables.
mjpeg: Huffman tables
rv10: additional flags
mpeg4: global headers (they can be in the bitstream or here)
=> OutputFile: copy extradata of codec context when create a new video stream

README.md, doc/code/index.doxygen
=> Readme: add link to doxygen doc

src/AvTranscoder/log.cpp, src/AvTranscoder/log.hpp
=> log: add private attribute to set header of logs only once

src/AvTranscoder/file/IOutputFile.hpp, src/AvTranscoder/file/OutputFile.cpp, src/AvTranscoder/file/OutputFile.hpp, src/AvTranscoder/mediaProperty/StreamProperties.cpp, src/AvTranscoder/mediaProperty/StreamProperties.hpp, src/AvTranscoder/stream/IInputStream.hpp, src/AvTranscoder/stream/IOutputStream.hpp, src/AvTranscoder/stream/InputStream.cpp, src/AvTranscoder/stream/InputStream.hpp, src/AvTranscoder/transcoder/StreamTranscoder.cpp, src/AvTranscoder/transcoder/Transcoder.cpp
=> IInputStream: add getProperties() method

src/AvTranscoder/decoder/AudioDecoder.cpp, src/AvTranscoder/decoder/VideoDecoder.cpp, src/AvTranscoder/encoder/AudioEncoder.cpp, src/AvTranscoder/encoder/VideoEncoder.cpp, src/AvTranscoder/file/FormatContext.cpp, src/AvTranscoder/file/FormatContext.hpp, src/AvTranscoder/file/InputFile.cpp, src/AvTranscoder/file/OutputFile.cpp, src/AvTranscoder/reader/IReader.cpp, test/pyTest/testOffset.py
=> Fix negative offset

src/AvTranscoder/file/FormatContext.cpp, src/AvTranscoder/file/OutputFile.cpp, src/AvTranscoder/file/OutputFile.hpp, test/pyTest/testEProcessMethod.py, test/pyTest/testNbFrames.py, test/pyTest/testNbSamples.py, test/pyTest/testOffset.py, test/pyTest/testOutputFile.py, test/pyTest/testProperties.py, test/pyTest/testSetFrame.py, test/pyTest/testTranscoderAdd.py, test/pyTest/testTranscoderDummy.py, test/pyTest/testTranscoderRewrap.py, test/pyTest/testTranscoderTranscodeAudioMov.py, test/pyTest/testTranscoderTranscodeAudioWave.py, test/pyTest/testTranscoderTranscodeVideo.py
=> OuputFile: can instanciate it without extension

src/AvTranscoder/mediaProperty/PixelProperties.cpp, src/AvTranscoder/mediaProperty/PixelProperties.hpp
=> PixelProperties: add getMaxBitPerChannel
